# Use an official Python runtime as a parent image
FROM continuumio/anaconda3:latest

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Create a Conda environment
RUN conda create -n myenv python=3.8.18 -y

# Make RUN commands use the new environment:
SHELL ["conda", "run", "-n", "myenv", "/bin/bash", "-c"]

# Install system dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    libpq-dev \
    pkg-config \
    libhdf5-dev \
    libsndfile1 \
    make \
    ffmpeg && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt /app/
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
# RUN pip install Cython==3.0.8
# RUN pip install youtokentome==1.0.6
# RUN pip install jiwer==3.0.3

# Expose the port Gunicorn will listen on
EXPOSE 8000

# The code to run when container is started:
CMD ["conda", "run", "-n", "myenv", "gunicorn", "--config", "gunicorn.conf.py", "tunetrust.wsgi:application"]

